"""empty message

Revision ID: 1c9bae9dc8ca
Revises: 6aa6ddb5a2be
Create Date: 2021-11-10 19:20:43.865302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9bae9dc8ca'
down_revision = '6aa6ddb5a2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_checkin', sa.Integer(), nullable=True))
    op.drop_column('users', 'last_checkIn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_checkIn', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_checkin')
    # ### end Alembic commands ###
