"""empty message

Revision ID: 216b5ba5fef4
Revises: a07c12ccd26d
Create Date: 2021-11-08 10:50:54.075409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216b5ba5fef4'
down_revision = 'a07c12ccd26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('server_members', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('server_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('server_members', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # op.create_primary_key('server_members', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_members', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('server_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('server_members', 'id')
    # ### end Alembic commands ###
