"""empty message

Revision ID: 98235673a8ec
Revises: 1c9bae9dc8ca
Create Date: 2021-11-11 10:49:42.620184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98235673a8ec'
down_revision = '1c9bae9dc8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon')
    # ### end Alembic commands ###
