"""empty message

Revision ID: 0a34f1de6ed5
Revises: a2c5f9a9b2b0
Create Date: 2021-11-12 12:40:57.637337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a34f1de6ed5'
down_revision = 'a2c5f9a9b2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('server_join', 'server_members', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('server_join', 'server_members', ['user_id', 'server_id'])
    # ### end Alembic commands ###
