"""empty message

Revision ID: 6aa6ddb5a2be
Revises: e1e0d7f2c7e0
Create Date: 2021-11-10 18:54:26.555113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa6ddb5a2be'
down_revision = 'e1e0d7f2c7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_checkIn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_checkIn')
    # ### end Alembic commands ###
