"""empty message

Revision ID: 04ae99c3ca8c
Revises: 0a34f1de6ed5
Create Date: 2021-11-12 12:44:32.224103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ae99c3ca8c'
down_revision = '0a34f1de6ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('server_join', 'server_members', ['user_id', 'server_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('server_join', 'server_members', type_='unique')
    # ### end Alembic commands ###
