"""empty message

Revision ID: e0e9f7127b3d
Revises: 216b5ba5fef4
Create Date: 2021-11-09 08:54:19.508635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e9f7127b3d'
down_revision = '216b5ba5fef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_name_key', 'channels', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('channels_name_key', 'channels', ['name'])
    # ### end Alembic commands ###
