"""empty message

Revision ID: 811501c8ce81
Revises: ddedc0d4597c
Create Date: 2021-11-12 12:07:19.099593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811501c8ce81'
down_revision = 'ddedc0d4597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_members', sa.Column('joined', sa.Boolean(), nullable=True))
    op.create_unique_constraint('server_join', 'server_members', ['user_id', 'server_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('server_join', 'server_members', type_='unique')
    op.drop_column('server_members', 'joined')
    # ### end Alembic commands ###
