"""empty message

Revision ID: 44508509d676
Revises: 98235673a8ec
Create Date: 2021-11-11 12:10:00.842415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44508509d676'
down_revision = '98235673a8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_checkIn', sa.String(length=100), nullable=True))
    op.drop_column('users', 'last_checkin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_checkin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_checkIn')
    # ### end Alembic commands ###
