"""empty message

Revision ID: a2c5f9a9b2b0
Revises: 811501c8ce81
Create Date: 2021-11-12 12:09:13.843781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c5f9a9b2b0'
down_revision = '811501c8ce81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_members', 'joined')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_members', sa.Column('joined', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
